export enum EquipmentType {
	BODY_TYPE,
	BODY_HAIRSTYLE,
	BODY_SKIN_COLOR,
	BODY_SKIN_TYPE,
	BODY_FACE_TYPE,
	WEAPON,
	CLOTHING_HEAD,
	CLOTHING_UPPERBODY,
	CLOTHING_LOWERBODY,
	CYBERWARE_EYES,
	CYBERWARE_SPINE,
	CYBERWARE_BONES,
	CYBERWARE_MUSCLES,
	CYBERWARE_ARMS,
	CYBERWARE_LEGS,
	CYBERWARE_SKIN,
	CYBERWARE_OTHER
}

export enum StatusEffectType {
	POISONED,
	BRUISED,
	CYBERVIRUS,
	HACKED,
	EXHAUSTED,
	OVERHEATED
}
